layers = {'Input': {"shape": (3,3,8), "name": "EFDC_inputs"},
          "Conv2D": {"filters": 15, "kernel_size": [2,2], "strides": (1,1), "padding": "same"},
          "BatchNormalization": {"epsilon": 0.001, "center": True, "scale": False, "momentum": 0.9},
          "crelu": {},
          "Conv2D_2": {"filters": 17, "kernel_size": [2,2], "padding": "same"},
          "BatchNormalization_2": {"epsilon": 0.001, "center": True, "scale": False, "momentum": 0.9},
          "crelu_2": {},
          "Conv2D_3": {"filters": 17, "kernel_size": [2,2], "padding": "same"},
          "BatchNormalization_3": {"epsilon": 0.001, "center": True, "scale": False, "momentum": 0.9},
          "crelu_3": {},
          "Conv2D_4": {"filters": 17, "kernel_size": [2,2], "padding": "same"},
          "BatchNormalization_4": {"epsilon": 0.001, "center": True, "scale": False, "momentum": 0.9},
          "crelu_4": {},

          "Dropout": 0.4,
          "Flatten": {},
          "Dense": {"units": 16, "activation": "crelu", "name": "efdc_outputs"},

          "Input_1": {"shape": (2160, 2), "name": "SWMM_inputs"},
          "Flatten_2": {"config": {},
          "inputs": "SWMM_inputs"},
#         "Dropout": 0.5
          "Dense_1": {"config": {"units": 17, "activation": "crelu"},
          "inputs": "Flatten_2"},
          "Dense_2": {"config": {"units": 16, "activation": "crelu"},
          "inputs": "Dense_1"},
          "Dense_3": {"config": {"units": 16, "activation": "crelu"},
          "inputs": "Dense_2"}, # add dense for test
#         "Flatten_3": {"config": {},
#         "inputs": "Dense_2"},
          "Dense_4": {"config": {"units": 16, "activation": "crelu", "name": "swmm_outputs"},
          "inputs": "Dense_3"},
          "Concatenate": {"config": {"axis": 1},
          "inputs": ["efdc_outputs", "swmm_outputs"]},
          "Dense_5": {"config": {"units": 16, "activation": "crelu"},
          "inputs": "Concatenate"},
          #"Dropout_1": 0.5,
          "Dense_6": {"config": {"units": 16, "activation": "crelu"},
          "inputs": "Dense_5"},
          "Dense_7": {"config": {"units": 16, "activation": "crelu"},
          "inputs": "Dense_6"},
          "Dropout_2": 0.3,
          "Dense_8": {"config": 1,"name": "model_output"}
          }